version: "3.3"

volumes:
    shared-workspace:
networks:
    spark-net:
        driver: bridge

services:
  spark-master:
    image: uqteaching/cloudcomputing:spark-master-v1
    container_name: spark-master
    networks:
        - "spark-net"
    ports:
        - "8080:8080"
        - "7077:7077"
    environment:
        - INIT_DAEMON_STEP=setup_spark
        - "PYSPARK_PYTHON=/usr/bin/python3"            
        - "PYSPARK_DRIVER_PYTHON=/usr/bin/python3"            
  
  spark-worker-1:
    image: uqteaching/cloudcomputing:spark-worker-v1
    container_name: spark-worker-1
    depends_on:
        - spark-master
    networks:
        - "spark-net"
    ports:
        - "8081:8081"
    environment:
        - "SPARK_MASTER=spark://spark-master:7077"            
        - "PYSPARK_PYTHON=/usr/bin/python3"            
        - "PYSPARK_DRIVER_PYTHON=/usr/bin/python3"            

  spark-worker-2:
    image: uqteaching/cloudcomputing:spark-worker-v1
    container_name: spark-worker-2
    depends_on:
        - spark-master
    networks:
        - "spark-net"
    ports:
        - "8082:8082"
    environment:
        - "SPARK_MASTER=spark://spark-master:7077"            
        - "PYSPARK_PYTHON=/usr/bin/python3"            
        - "PYSPARK_DRIVER_PYTHON=/usr/bin/python3"            
  
  jupyter-notebook:
    container_name: jupyternb
    image: jupyter/all-spark-notebook
    depends_on:
        - spark-master
    expose:
        - "8888"
    networks:
        - "spark-net"
    ports:
        - "8888:8888"
    volumes:
        - ./nbs:/home/jovyan/work/nbs
        - ./events:/tmp/spark-events
    environment:
        - "PYSPARK_PYTHON=/usr/bin/python3"            
        - "PYSPARK_DRIVER_PYTHON=/usr/bin/python3"            
    command: "start-notebook.sh \
          --ip=0.0.0.0 \
          --allow-root \
          --notebook-dir=/home/jovyan/work/nbs \
          --NotebookApp.token=''  
          "

